inherit_from:
  - https://bitbucket.org/bsm/misc/raw/master/rubocop/default.yml

Security/Open:
  Exclude:
    - "core/lib/bfs/bucket/abstract.rb"
    - "core/lib/bfs/blob.rb"
Metrics/BlockLength:
  Exclude:
    - "**/spec/**/*"
